name: Build KernelSU

on:

  push:

    branches: ["twelve"]

  workflow_dispatch:

jobs:

  build:

    strategy:

      matrix:

        device: [m23xq]

        

    name: Build KernelSU-${{ matrix.device }}

    runs-on: ubuntu-latest

    env:

      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"

      CCACHE_NOHASHDIR: "true"

      CCACHE_HARDLINK: "true"

    

    steps:

      - name: Installing Dependencies

        run: |

          sudo apt update -y

          sudo apt-get install -y lld binutils clang llvm zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full ccache

          sudo apt clean

          

      - name: Checkout

        uses: actions/checkout@v3

        

      - name: Cache Build Tools

        id: cache-aosp-clang

        uses: actions/cache@v3

        with:

          path: aosp-clang

          key: aosp-clang  

        

      - name: Download Build Tools

        if: steps.cache-aosp-clang.outputs.cache-hit != 'true'

        run: |

          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=1 --single-branch --no-tags -b master aosp-clang/clang

          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags aosp-clang/aarch64-linux-android-4.9

          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags aosp-clang/arm-linux-androideabi-4.9

      

      - name: Setup kernel source

        uses: actions/checkout@v3

        with:

          submodules: true

          repository: Aflaungos/android_kernel_samsung_m23xq

          ref: twelve

          path: kernel-source

          

      - name: Checkout Anykernel

        uses: actions/checkout@v3

        with:

          submodules: true

          repository: Aflaungos/AnyKernel3

          ref: master

          path: anykernel     

      

       #- name: Setup KernelSU

       #  working-directory: kernel-source

       #  run: |

       #     git config --global user.email "vimavick@gmail.com"

       #     git config --global user.name "mrsiri"

       #     curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

       #    

       #     cd KernelSU

       #     echo "KSU_VERSION=$(($(git rev-list --count HEAD) + 10200))" >> $GITHUB_ENV

       #     cd -

      - name: Setup Ccache

        uses: hendrikmuhs/ccache-action@v1.2

        with:

          key: Build-KernelSU-${{ matrix.device }}

          save: ${{ github.event_name != 'pull_request' }}

          max-size: 2G

          

      - name: Build Kernel

        working-directory: kernel-source

        run: |

          CLANG="$GITHUB_WORKSPACE/aosp-clang/clang/clang-r487747/bin"

          GCC32="$GITHUB_WORKSPACE/aosp-clang/arm-linux-androideabi-4.9/bin"

          GCC64="$GITHUB_WORKSPACE/aosp-clang/aarch64-linux-android-4.9/bin"

          PATH=$CLANG:$GCC64:$GCC32:$PATH

          export PATH

          export ARCH=arm64

          export CLANG_TRIPLE=aarch64-linux-gnu

          export CROSS_COMPILE=aarch64-linux-android-

          export CROSS_COMPILE_ARM32=arm-linux-androideabi-

          output_dir=out

          date=$(date +"%Y%m%d%H%M")

          export PATH="/usr/lib/ccache:$PATH"

          echo "date=$date" >> $GITHUB_ENV

          echo "Building kernel with $args"  

          make O=out LLVM=1 LLVM_IAS=1 CC="ccache clang" lineageos_${{ matrix.device }}_defconfig && make O=out LLVM=1 LLVM_IAS=1 CC="ccache clang" -j$(grep -c ^processor /proc/cpuinfo)

          

      - name: Upload KernelSU-${{ matrix.device }}

        uses: actions/upload-artifact@v3

        with:

          name: KernelSU-${{ matrix.device }}

          path: kernel-source/out/arch/arm64/boot/*

          

      - name: Prepare Anykernel

        working-directory: anykernel

        run: |

          cp -f $GITHUB_WORKSPACE/kernel-source/out/arch/arm64/boot/Image.gz-dtb .

          ZIP_NAME="KernelSU-v-${{ env.KSU_VERSION }}-${{ matrix.device }}-${{ env.date }}"

          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

          zip -r "$ZIP_NAME.zip" *

          mv "$ZIP_NAME.zip" $GITHUB_WORKSPACE

          

      - name: Upload Anykernel

        uses: actions/upload-artifact@v3

        with:

          name: ${{ env.ZIP_NAME }}

          path: anykernel/*

          

      - name: Creating Config Info

        run: |

          echo "Device: Evert"

          Device: ${{ matrix.device }}

          Build Code: v-${{ env.KSU_VERSION }}-$(date +%Y%m%d)_${{ github.run_number }}

          Only For Stock Based Roms

          " >> INFO.txt

      

      - name: Release

        if: success()

        uses: softprops/action-gh-release@v1

        with:

          name: "KernelSU For ${{ matrix.device }}"

          body_path: "INFO.txt"

          files: |

            kernel-source/out/arch/arm64/boot/*

            ${{ env.ZIP_NAME }}.zip

          tag_name: ${{ github.run_number }}-${{ github.ref }}-${{ matrix.device }}

          

      - name: Setup mutex for uploading

        uses: ben-z/gh-action-mutex@v1.0-alpha-7

        if: github.event_name != 'pull_request' && steps.need_upload.outputs.UPLOAD == 'true'

      - name: Upload to telegram

        if: github.event_name != 'pull_request' && steps.need_upload.outputs.UPLOAD == 'true'

        env:

          CHAT_ID: ${{ secrets.CHAT_ID }}

          CACHE_CHAT_ID: ${{ secrets.CACHE_CHAT_ID }}

          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}

          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

          COMMIT_URL: ${{ github.event.head_commit.url }}

          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          TITLE: Manager

        run: |

          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then

            export VERSION=$(git rev-list --count HEAD)

            APK=$(find ./app/build/outputs/apk/release -name "*.apk")

            pip3 install python-telegram-bot

            python3 $GITHUB_WORKSPACE/scripts/ksubot.py $APK

          fi

          

      - name: Delete workflow runs

        uses: Mattraks/delete-workflow-runs@v2

        with:

          retain_days: 0

          keep_minimum_runs: 2
